#!/usr/bin/env bash
#
#    10-sysinfo - generate the system information
#    Copyright (c) 2013 Nick Charlton
#
#    Authors: Nick Charlton <hello@nickcharlton.net>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#####################################################
# Updated by afiniel for crypto use...
#####################################################


date=`date`
divider===============================
divider=$divider$divider
header=" %-7s %-25s %-16s %-15s\n"
width=50
RED=$'\033[00;31m'
GREEN=$'\033[00;32m'
RESTORE=$'\033[0m'
echo "System information as of: $date"
echo
/usr/bin/landscape-sysinfo
echo
echo "YiiMP Information:"
printf "%$width.${width}s\n" "$divider"
printf "$header" $RED"Warning:"$RESTORE "You are logged in to your db server"
printf "$header" $RED"Warning:"$RESTORE $GREEN"All changes should be made through your web server"$RESTORE
echo
echo "To reload this MOTD just type motd..."
echo
echo "Donations for continued support of this script are welcomed at:"
echo
echo "BTC bc1qpnxtg3dvtglrvfllfk3gslt6h5zffkf069nh8r"
echo "DOGE DCj73fKJbHeDTJx7arz4z7bbknWkSDpD8h"
echo "ETH 0x50C7d0BF9714dBEcDc1aa6Ab0E72af8e6Ce3b0aB"
echo "LTC ltc1qqw7cv4snx9ctmpcf25x26lphqluly4w6m073qw"
echo
/usr/lib/update-notifier/update-motd-reboot-required
/usr/lib/update-notifier/apt-check --human-readable
echo
